---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: &app lldap
  labels:
    app.kubernetes.io/name: *app
spec:
  selector:
    app.kubernetes.io/name: *app
  ports:
    - name: ldap
      port: 389
      targetPort: ldap
      protocol: TCP
    - name: webui
      port: 17170
      targetPort: webui
      protocol: TCP
