---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: token
      remoteRef:
        key: SEERR_API_TOKEN
  target:
    name: seerr
    creationPolicy: Owner
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-db
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: username
      remoteRef:
        key: SEERR_DB_USERNAME
    - secretKey: password
      remoteRef:
        key: SEERR_DB_PASSWORD
  target:
    name: seerr-db
    creationPolicy: Owner
