---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/cronjob-batch-v1.json
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jellyfin
spec:
  schedule: 0 8 * * * # daily
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 600
      template:
        spec:
          restartPolicy: Never
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: refresh-images
              image: quay.io/curl/curl:8.21.0@sha256:7c12af72ceb38b7432ab85e1a265cff6ae58e06f95539d539b654f2cfa64bb13
              command:
                - /bin/sh
                - -c
                - /bin/script.sh
              resources:
                requests:
                  cpu: 10m
                  memory: 128M
                limits:
                  memory: 128M
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: {drop: ["ALL"]}
              env:
                - name: JELLYFIN_URL
                  value: http://watch.${domain}.${tld}
                - name: JELLYFIN_ADMIN_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: jellyfin
                      key: JELLYFIN_ADMIN_USERNAME
                - name: JELLYFIN_ADMIN_USER_ID
                  valueFrom:
                    secretKeyRef:
                      name: jellyfin
                      key: JELLYFIN_ADMIN_USER_ID
                - name: JELLYFIN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: jellyfin
                      key: JELLYFIN_API_KEY
              volumeMounts:
                - name: script
                  mountPath: /bin/script.sh
                  subPath: script.sh
                  readOnly: true
                - name: jq
                  mountPath: /tools
          volumes:
            - name: script
              configMap:
                name: script
                defaultMode: 0755
            - name: jq
              image:
                reference: ghcr.io/jqlang/jq:1.8.2@sha256:b9c68867e5766576263a222e91db3de422d802069c7af70440e667a95344e486
