---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-proxy
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: MINECRAFT_PROXY_SECRET
      remoteRef:
        key: MINECRAFT_PROXY_SECRET
  target:
    name: minecraft-proxy
    creationPolicy: Owner
