---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookboss
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: BOOKBOSS_OIDC_PASSWORD
      remoteRef:
        key: BOOKBOSS_OIDC_PASSWORD
    - secretKey: BOOKBOSS_ENCRYPTION_SECRET
      remoteRef:
        key: BOOKBOSS_ENCRYPTION_SECRET
    - secretKey: HARDCOVER_API_KEY
      remoteRef:
        key: HARDCOVER_API_KEY
    - secretKey: BOOKBOSS_DB_USERNAME
      remoteRef:
        key: BOOKBOSS_DB_USERNAME
    - secretKey: BOOKBOSS_DB_PASSWORD
      remoteRef:
        key: BOOKBOSS_DB_PASSWORD
  target:
    name: bookboss
    creationPolicy: Owner
