---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: TANDOOR_DB_USERNAME
      remoteRef:
        key: TANDOOR_DB_USERNAME
    - secretKey: TANDOOR_DB_PASSWORD
      remoteRef:
        key: TANDOOR_DB_PASSWORD
    - secretKey: TANDOOR_ENCRYPTION_SECRET
      remoteRef:
        key: TANDOOR_ENCRYPTION_SECRET
  target:
    name: tandoor
    creationPolicy: Owner
