---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name deduparr
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  refreshPolicy: Periodic
  refreshInterval: 1h
  data:
    - secretKey: RADARR_API_TOKEN
      remoteRef:
        key: RADARR_API_TOKEN
    - secretKey: SONARR_API_TOKEN
      remoteRef:
        key: SONARR_API_TOKEN
  target:
    name: *name
    creationPolicy: Owner
